name: 05 - 2 - Event Filters and Activity
on: workflow_dispatch
#  pull_request: 
#    types:
#      - closed
#    branches:
#      - master
jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo Running whenever a PR is closed.